parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    _instanceof:
        App\DataProcessor\DataProcessorInterface:
            tags: ['app.data_processor']
when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Service\DataService:
            public: true
